/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Josep
 */
public class ManterClienteView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarEditarCliente
     */
    public ManterClienteView() {
        initComponents();
    }

    public JTextField getJTextFieldDocumentoCliente() {
        return JTextFieldDocumentoCliente;
    }

    public JTextField getJTextFieldNomeCliente() {
        return JTextFieldNomeCliente;
    }

    public JTextField getJTextFieldTelefoneCliente() {
        return JTextFieldTelefoneCliente;
    }

    public JButton getjButtonEditar() {
        return jButtonEditar;
    }

    public JButton getjButtonExcluir() {
        return jButtonExcluir;
    }

    public JButton getjButtonFechar() {
        return jButtonFechar;
    }

    public JLabel getjLabelDocumentoTipo() {
        return jLabelDocumentoTipo;
    }

    public JLabel getjLabelavisodocumento() {
        return jLabelavisodocumento;
    }

    public JLabel getjLabelavisotelefone() {
        return jLabelavisotelefone;
    }
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabelavisotelefone = new javax.swing.JLabel();
        JTextFieldTelefoneCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelavisodocumento = new javax.swing.JLabel();
        JTextFieldDocumentoCliente = new javax.swing.JTextField();
        JTextFieldNomeCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelDocumentoTipo = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(570, 315));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExcluir.setText("Excluir");
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 120, -1));

        jButtonEditar.setText("Editar");
        getContentPane().add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 120, -1));

        jButtonFechar.setText("Fechar");
        getContentPane().add(jButtonFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 120, -1));

        jLabelavisotelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelavisotelefone.setText("(xx)xxxxx-xxxx ou (xx)xxxx-xxxx");
        getContentPane().add(jLabelavisotelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));
        getContentPane().add(JTextFieldTelefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 359, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Telefone");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CPF/CNPJ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabelavisodocumento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelavisodocumento.setText("Somente números");
        getContentPane().add(jLabelavisodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));
        getContentPane().add(JTextFieldDocumentoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, -1));
        getContentPane().add(JTextFieldNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 360, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 57, 23));

        jLabelDocumentoTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDocumentoTipo.setText("jLabel4");
        getContentPane().add(jLabelDocumentoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextFieldDocumentoCliente;
    private javax.swing.JTextField JTextFieldNomeCliente;
    private javax.swing.JTextField JTextFieldTelefoneCliente;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDocumentoTipo;
    private javax.swing.JLabel jLabelavisodocumento;
    private javax.swing.JLabel jLabelavisotelefone;
    // End of variables declaration//GEN-END:variables
}
